import { z } from "zod";
import { PracticeAttemptSchema, PracticeQuestionSchema } from "../types/practiceAttempt.types";

// userId comes from the auth token, startedAt is stamped by the service, and
// questions are now generated by FastAPI (see PracticeAttemptService.startAttempt)
// rather than supplied by the client.
export const StartPracticeAttemptDtoSchema = PracticeAttemptSchema.pick({
  jobRoleId: true,
  skill: true,
  difficulty: true,
  mode: true,
  questionCount: true,
});

// The client submits the raw answer (transcribed text for oral, source code
// for coding); score/confidenceScore/feedback/expectedAnswer are computed by
// FastAPI's evaluate endpoint inside the service, not supplied here.
export const SubmitAnswerDtoSchema = z.object({
  questionIndex: z.number().int().nonnegative(),
  userAnswer: z.string().default(""),
  userCode: z.string().nullable().optional(),
});

// No scores here either -- completeAttempt averages each question's
// score/confidenceScore into the attempt-level technicalScore/
// communicationScore. feedback/recommendations are optional free-text the
// client can attach (e.g. a self-reflection note); nothing generates an
// AI-written overall session review yet.
export const CompletePracticeAttemptDtoSchema = z.object({
  feedback: z.string().default(""),
  recommendations: z.array(z.string()).default([]),
});

export type StartPracticeAttemptDto = z.infer<typeof StartPracticeAttemptDtoSchema>;
export type SubmitAnswerDto = z.infer<typeof SubmitAnswerDtoSchema>;
export type CompletePracticeAttemptDto = z.infer<typeof CompletePracticeAttemptDtoSchema>;
export type PracticeQuestionDto = z.infer<typeof PracticeQuestionSchema>;
