[project]
name = "ai-services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "audioop-lts>=0.2.2",
    "beautifulsoup4>=4.15.0",
    "bs4>=0.0.2",
    "fastapi>=0.139.0",
    "generativeai>=0.0.1",
    "google-genai>=2.11.0",
    "groq>=1.5.0",
    "httpx>=0.28.1",
    "imageio-ffmpeg>=0.6.0",
    "openai-whisper>=20250625",
    "playwright>=1.61.0",
    "pydantic>=2.13.4",
    "pypdf>=6.0.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "uvicorn>=0.51.0",
]
